### ISSUE TITLE
Message queues necessary?

### ISSUE THREAD

**Issue by rrjanbiah** [lawrencejones/pgsink#164]
Found this project through HN. Looks great as it doesn't require JVM as in debezium.

In order to effectively use `pgsink`, do we need any message queues (NATS or liftbridge in Go ecosystem)?

_Apologies, if this question is naive_

**Comment by lawrencejones** [comment]
Hey! I somehow missed this issue entirely, so sorry for the tardy response.

> In order to effectively use pgsink, do we need any message queues (NATS or liftbridge in Go ecosystem)?

There's no message queue required, or any dependency other than the Postgres database itself. pgsink tracks its state in a `pgsink` schema on the database it streams from, so it's almost dependency-less.

I'm a couple of weeks away from the project being useable, after which I'll cut a prototype release and complete some documentation efforts on how it's built (#45).

**Comment by lawrencejones** [comment]
So I guess we can close this, as no, we don't have any message queues.

**Comment by rrjanbiah** [comment]
@lawrencejones Thanks for your reply.

> There's no message queue required

If true, it will be a huge hit. Expect a crazy traffic once you launch :-) Also, for a CDC use case (#165), it will kill all other tools in this space!

FWIW... checked https://github.com/lawrencejones/pgsink/pull/45/files I'm not technically sound here in PostgreSQL. But, it seems to be similar to the Hasura subscriptions (?) If so, I'd like to give a heads up to some known issues there https://github.com/hasura/graphql-engine/issues/2907#issuecomment-539477677 (plus, linked issues and comments)
